<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[C:\SVNatNCI_old\PEDAL_QTP\tst\ST_Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[ST_Driver]]></DName>
<Res><![CDATA[Res11]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:50]]></Time>
<TimeTick>1292967650</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:50]]></Time>
<TimeTick>1292967650</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA["SEARCH MODELS"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=SEARCH MODELS<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (16 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=SEARCH MODELS<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>class=footerMenuLink<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=SEARCH MODELS<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=http://cancermodels-qa.nci.nih.gov/camod/SimpleSearchPopulateAction.do;jsessionid=CFD9108AFB6E44A45FFEB640C665879D?unprotected_method=populate<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:50]]></Time>
<TimeTick>1292967650</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" MovieMarker="MARK178" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["SEARCH MODELS"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SEARCH MODELS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:50]]></Time>
<TimeTick>1292967650</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" MovieMarker="MARK179" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SEARCH MODELS.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:50]]></Time>
<TimeTick>1292967650</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:50]]></Time>
<TimeTick>1292967650</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" MovieMarker="MARK180" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:51]]></Time>
<TimeTick>1292967651</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:51]]></Time>
<TimeTick>1292967651</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" MovieMarker="MARK181" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Nutrition"]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:52]]></Time>
<TimeTick>1292967652</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" MovieMarker="MARK182" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:53]]></Time>
<TimeTick>1292967653</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" MovieMarker="MARK183" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Unique Model Identifier_17]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test11.xls
Row: 7
Expected value: 
575
Matched actual value: 
575]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:53]]></Time>
<TimeTick>1292967653</TimeTick>
<NodeArgs eType="User" icon="10" nRep="28" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_17]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="19" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:53]]></Time>
<TimeTick>1292967653</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:53]]></Time>
<TimeTick>1292967653</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" MovieMarker="MARK184" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:54]]></Time>
<TimeTick>1292967654</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:54]]></Time>
<TimeTick>1292967654</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" MovieMarker="MARK185" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Nutrition"]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:55]]></Time>
<TimeTick>1292967655</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" MovieMarker="MARK186" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["vitamin E (RRR-a-tocopherol)"]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:55]]></Time>
<TimeTick>1292967655</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="42" MovieMarker="MARK187" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentName.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:55]]></Time>
<TimeTick>1292967655</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="45" MovieMarker="MARK188" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Unique Model Identifier_17]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test11.xls
Row: 13
Expected value: 
575
Matched actual value: 
575]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:56]]></Time>
<TimeTick>1292967656</TimeTick>
<NodeArgs eType="User" icon="10" nRep="47" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_17]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="35" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:56]]></Time>
<TimeTick>1292967656</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:56]]></Time>
<TimeTick>1292967656</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" MovieMarker="MARK189" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:56]]></Time>
<TimeTick>1292967656</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:56]]></Time>
<TimeTick>1292967656</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" MovieMarker="MARK190" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Other"]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:57]]></Time>
<TimeTick>1292967657</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" MovieMarker="MARK191" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:58]]></Time>
<TimeTick>1292967658</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" MovieMarker="MARK192" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Unique Model Identifier_23]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test11.xls
Row: 18
Expected value: 
50058862
Matched actual value: 
50058862]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:59]]></Time>
<TimeTick>1292967659</TimeTick>
<NodeArgs eType="User" icon="10" nRep="63" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_23]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="54" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:59]]></Time>
<TimeTick>1292967659</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:40:59]]></Time>
<TimeTick>1292967659</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" MovieMarker="MARK193" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="66" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:00]]></Time>
<TimeTick>1292967660</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:00]]></Time>
<TimeTick>1292967660</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="71" MovieMarker="MARK194" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Other"]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:01]]></Time>
<TimeTick>1292967661</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" MovieMarker="MARK195" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["thymectomy"]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:01]]></Time>
<TimeTick>1292967661</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" MovieMarker="MARK196" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentName.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:01]]></Time>
<TimeTick>1292967661</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" MovieMarker="MARK197" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Unique Model Identifier_24]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test11.xls
Row: 24
Expected value: 
50064831
Matched actual value: 
50064831]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:02]]></Time>
<TimeTick>1292967662</TimeTick>
<NodeArgs eType="User" icon="10" nRep="82" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_24]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="70" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:02]]></Time>
<TimeTick>1292967662</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:02]]></Time>
<TimeTick>1292967662</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="86" MovieMarker="MARK198" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="85" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:03]]></Time>
<TimeTick>1292967663</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:03]]></Time>
<TimeTick>1292967663</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" MovieMarker="MARK199" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Plasmid"]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:03]]></Time>
<TimeTick>1292967663</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="93" MovieMarker="MARK200" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:04]]></Time>
<TimeTick>1292967664</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="96" MovieMarker="MARK201" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Unique Model Identifier_25]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test11.xls
Row: 29
Expected value: 
50062696
Matched actual value: 
50062696]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:05]]></Time>
<TimeTick>1292967665</TimeTick>
<NodeArgs eType="User" icon="10" nRep="98" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_25]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="89" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:05]]></Time>
<TimeTick>1292967665</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:05]]></Time>
<TimeTick>1292967665</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="102" MovieMarker="MARK202" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="101" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:06]]></Time>
<TimeTick>1292967666</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:06]]></Time>
<TimeTick>1292967666</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="106" MovieMarker="MARK203" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Plasmid"]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:06]]></Time>
<TimeTick>1292967666</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="109" MovieMarker="MARK204" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["control plasmid pPGK"]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:07]]></Time>
<TimeTick>1292967667</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="112" MovieMarker="MARK205" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentName.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:07]]></Time>
<TimeTick>1292967667</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" MovieMarker="MARK206" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[Unique Model Identifier_25]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test11.xls
Row: 35
Expected value: 
50062696
Matched actual value: 
50062696]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:08]]></Time>
<TimeTick>1292967668</TimeTick>
<NodeArgs eType="User" icon="10" nRep="117" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_25]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Test Case elapsed Time]]></Obj>
<Details ><![CDATA[TestCaseElapsedTime: 21.919seconds]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:08]]></Time>
<TimeTick>1292967668</TimeTick>
<NodeArgs eType="User" icon="10" nRep="118" status="Information" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Test Case elapsed Time]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54" retval=" ">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/21/2010 - 16:41:08]]></Time>
<TimeTick>1292967668</TimeTick>
<NodeArgs eType="General" icon="11" nRep="119" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="105" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/21/2010 - 16:40:32" eTime="12/21/2010 - 16:41:08" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" MovieMarker="MARK177" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="12/21/2010 - 16:40:31" eTime="12/21/2010 - 16:41:08" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test ST_Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>