<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[C:\SVNatNCI_old\PEDAL_QTP\tst\ST_Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[ST_Driver]]></DName>
<Res><![CDATA[Res9]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:32]]></Time>
<TimeTick>1292967572</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:32]]></Time>
<TimeTick>1292967572</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA["SEARCH MODELS"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=SEARCH MODELS<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (16 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=SEARCH MODELS<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>class=footerMenuLink<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=SEARCH MODELS<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=http://cancermodels-qa.nci.nih.gov/camod/SimpleSearchPopulateAction.do;jsessionid=CFD9108AFB6E44A45FFEB640C665879D?unprotected_method=populate<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:32]]></Time>
<TimeTick>1292967572</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" MovieMarker="MARK148" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["SEARCH MODELS"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SEARCH MODELS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:32]]></Time>
<TimeTick>1292967572</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" MovieMarker="MARK149" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SEARCH MODELS.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:33]]></Time>
<TimeTick>1292967573</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:33]]></Time>
<TimeTick>1292967573</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" MovieMarker="MARK150" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:34]]></Time>
<TimeTick>1292967574</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:34]]></Time>
<TimeTick>1292967574</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" MovieMarker="MARK151" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Antibody"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:34]]></Time>
<TimeTick>1292967574</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" MovieMarker="MARK152" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:35]]></Time>
<TimeTick>1292967575</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" MovieMarker="MARK153" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Unique Model Identifier_11]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test09.xls
Row: 7
Expected value: 
50062857
Matched actual value: 
50062857]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:36]]></Time>
<TimeTick>1292967576</TimeTick>
<NodeArgs eType="User" icon="10" nRep="28" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_11]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="19" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:36]]></Time>
<TimeTick>1292967576</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:36]]></Time>
<TimeTick>1292967576</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" MovieMarker="MARK154" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:36]]></Time>
<TimeTick>1292967576</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:36]]></Time>
<TimeTick>1292967576</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" MovieMarker="MARK155" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Antibody"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:37]]></Time>
<TimeTick>1292967577</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" MovieMarker="MARK156" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["anti-CTLA-4 antibody"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:37]]></Time>
<TimeTick>1292967577</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="42" MovieMarker="MARK157" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentName.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:38]]></Time>
<TimeTick>1292967578</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="45" MovieMarker="MARK158" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Unique Model Identifier_12]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test09.xls
Row: 13
Expected value: 
50062857
Matched actual value: 
50062857]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:38]]></Time>
<TimeTick>1292967578</TimeTick>
<NodeArgs eType="User" icon="10" nRep="47" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_12]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="35" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:38]]></Time>
<TimeTick>1292967578</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:38]]></Time>
<TimeTick>1292967578</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" MovieMarker="MARK159" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:39]]></Time>
<TimeTick>1292967579</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:39]]></Time>
<TimeTick>1292967579</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" MovieMarker="MARK160" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Bacteria"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:40]]></Time>
<TimeTick>1292967580</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" MovieMarker="MARK161" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:40]]></Time>
<TimeTick>1292967580</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" MovieMarker="MARK162" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Unique Model Identifier_13]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test09.xls
Row: 18
Expected value: 
50063418
Matched actual value: 
50063418]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:41]]></Time>
<TimeTick>1292967581</TimeTick>
<NodeArgs eType="User" icon="10" nRep="63" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_13]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="54" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:41]]></Time>
<TimeTick>1292967581</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:41]]></Time>
<TimeTick>1292967581</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" MovieMarker="MARK163" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="66" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:42]]></Time>
<TimeTick>1292967582</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:42]]></Time>
<TimeTick>1292967582</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="71" MovieMarker="MARK164" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Bacteria"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:43]]></Time>
<TimeTick>1292967583</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" MovieMarker="MARK165" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["helicobacter felis"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:43]]></Time>
<TimeTick>1292967583</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" MovieMarker="MARK166" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentName.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:43]]></Time>
<TimeTick>1292967583</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" MovieMarker="MARK167" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Unique Model Identifier_14]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test09.xls
Row: 24
Expected value: 
50064639
Matched actual value: 
50064639]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:44]]></Time>
<TimeTick>1292967584</TimeTick>
<NodeArgs eType="User" icon="10" nRep="82" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_14]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="70" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:44]]></Time>
<TimeTick>1292967584</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:44]]></Time>
<TimeTick>1292967584</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="86" MovieMarker="MARK168" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="85" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:44]]></Time>
<TimeTick>1292967584</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:44]]></Time>
<TimeTick>1292967584</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" MovieMarker="MARK169" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Chemical / Drug"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:45]]></Time>
<TimeTick>1292967585</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="93" MovieMarker="MARK170" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:46]]></Time>
<TimeTick>1292967586</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="96" MovieMarker="MARK171" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Unique Model Identifier_15]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test09.xls
Row: 29
Expected value: 
20
Matched actual value: 
20]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:50]]></Time>
<TimeTick>1292967590</TimeTick>
<NodeArgs eType="User" icon="10" nRep="98" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_15]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="89" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:51]]></Time>
<TimeTick>1292967591</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:51]]></Time>
<TimeTick>1292967591</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="102" MovieMarker="MARK172" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="101" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:51]]></Time>
<TimeTick>1292967591</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:51]]></Time>
<TimeTick>1292967591</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="106" MovieMarker="MARK173" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Chemical / Drug"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:52]]></Time>
<TimeTick>1292967592</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="109" MovieMarker="MARK174" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["acetone"]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:52]]></Time>
<TimeTick>1292967592</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="112" MovieMarker="MARK175" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentName.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:53]]></Time>
<TimeTick>1292967593</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" MovieMarker="MARK176" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[Unique Model Identifier_16]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test09.xls
Row: 35
Expected value: 
50062290
Matched actual value: 
50062290]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:53]]></Time>
<TimeTick>1292967593</TimeTick>
<NodeArgs eType="User" icon="10" nRep="117" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Test Case elapsed Time]]></Obj>
<Details ><![CDATA[TestCaseElapsedTime: 24.84seconds]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:53]]></Time>
<TimeTick>1292967593</TimeTick>
<NodeArgs eType="User" icon="10" nRep="118" status="Information" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Test Case elapsed Time]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54" retval=" ">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/21/2010 - 16:39:54]]></Time>
<TimeTick>1292967594</TimeTick>
<NodeArgs eType="General" icon="11" nRep="119" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="105" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/21/2010 - 16:39:19" eTime="12/21/2010 - 16:39:54" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" MovieMarker="MARK147" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="12/21/2010 - 16:39:18" eTime="12/21/2010 - 16:39:54" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test ST_Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>