<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[H:\KambampatiM\Automation\caMOD\Admin Modify Model Characteristics]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Admin Modify Model Characteristics]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[ModelCharacteristics]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:02]]></Time>
<TimeTick>1293047282</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:02]]></Time>
<TimeTick>1293047282</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:02]]></Time>
<TimeTick>1293047282</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" MovieMarker="MARK16" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[ModelCharacteristics]]></Obj>
<Details ><![CDATA[caMOD application page opened.]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:02]]></Time>
<TimeTick>1293047282</TimeTick>
<NodeArgs eType="User" icon="7" nRep="12" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ModelCharacteristics]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:03]]></Time>
<TimeTick>1293047283</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ADMINISTRATION.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:03]]></Time>
<TimeTick>1293047283</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" MovieMarker="MARK17" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ADMINISTRATION.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:03]]></Time>
<TimeTick>1293047283</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" MovieMarker="MARK18" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:03]]></Time>
<TimeTick>1293047283</TimeTick>
<NodeArgs eType="General" icon="8" nRep="20" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="22" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="24" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="26" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="28" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="30" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="32" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="34" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="36" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="General" icon="8" nRep="38" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[ModelCharacteristics]]></Obj>
<Details ><![CDATA[User logged into caMOD with SuperUser role.]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="User" icon="7" nRep="39" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ModelCharacteristics]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:04]]></Time>
<TimeTick>1293047284</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" MovieMarker="MARK19" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="42" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:05]]></Time>
<TimeTick>1293047285</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[EDIT MODELS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:05]]></Time>
<TimeTick>1293047285</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" MovieMarker="MARK20" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[EDIT MODELS.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_5]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:05]]></Time>
<TimeTick>1293047285</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:05]]></Time>
<TimeTick>1293047285</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="51" MovieMarker="MARK21" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[modelId.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["150067374"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:06]]></Time>
<TimeTick>1293047286</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" MovieMarker="MARK22" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[modelId.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Search by Model Id.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:06]]></Time>
<TimeTick>1293047286</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" MovieMarker="MARK23" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[Search by Model Id.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["No."- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (19 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebTable<br>html tag=TABLE<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (19 objects found)&nbsp;</FONT></u><br>
micclass=WebTable<br>html tag=TABLE<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=row<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>border=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:06]]></Time>
<TimeTick>1293047286</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="59" MovieMarker="MARK24" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA["No."- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["No.":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:06]]></Time>
<TimeTick>1293047286</TimeTick>
<NodeArgs eType="General" icon="8" nRep="60" >
<Disp><![CDATA["No.":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ A1A1A1A1 Test Model  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:07]]></Time>
<TimeTick>1293047287</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="63" MovieMarker="MARK25" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[[ A1A1A1A1 Test Model  ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_5]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_6]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:07]]></Time>
<TimeTick>1293047287</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[MODEL CHARACTERISTICS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:07]]></Time>
<TimeTick>1293047287</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="67" MovieMarker="MARK26" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[MODEL CHARACTERISTICS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ A1A1A1A1 Test Model ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:08]]></Time>
<TimeTick>1293047288</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="70" MovieMarker="MARK27" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[[ A1A1A1A1 Test Model ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="66" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_6]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:08]]></Time>
<TimeTick>1293047288</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[modelDescriptor.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Model_10082010 Modified"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:08]]></Time>
<TimeTick>1293047288</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="74" MovieMarker="MARK28" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[modelDescriptor.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[principalInvestigator.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Wagner, Ulli"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:08]]></Time>
<TimeTick>1293047288</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="77" MovieMarker="MARK29" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[principalInvestigator.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[isToolStrain.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["no"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:08]]></Time>
<TimeTick>1293047288</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="80" MovieMarker="MARK30" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[isToolStrain.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[scientificName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Cattle (Bos taurus)"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:09]]></Time>
<TimeTick>1293047289</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="83" MovieMarker="MARK31" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[scientificName.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="73" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_8]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:09]]></Time>
<TimeTick>1293047289</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[ethinicityStrain.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Not specified"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:09]]></Time>
<TimeTick>1293047289</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="87" MovieMarker="MARK32" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ethinicityStrain.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[ethinicityStrain.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:09]]></Time>
<TimeTick>1293047289</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="90" MovieMarker="MARK33" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ethinicityStrain.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[ethinicityStrain.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:09]]></Time>
<TimeTick>1293047289</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="93" MovieMarker="MARK34" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ethinicityStrain.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[genotype.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test Genotype"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:09]]></Time>
<TimeTick>1293047289</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="96" MovieMarker="MARK35" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[genotype.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[nomenclature.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test Nomenclature"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="99" MovieMarker="MARK36" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[nomenclature.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[experimentDesign.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test comments on Experimental Design"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="102" MovieMarker="MARK37" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[experimentDesign.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[description.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test Comments on Phenotype - modified"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="105" MovieMarker="MARK38" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[description.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[type.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Male Only"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="108" MovieMarker="MARK39" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[type.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[breedingNotes.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test notes on Breeding"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="111" MovieMarker="MARK40" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[breedingNotes.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[url.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["www.test.com"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="114" MovieMarker="MARK41" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[url.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[releaseDate.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["immediately"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="117" MovieMarker="MARK42" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[releaseDate.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[comments.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test comments on Comment section."]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="120" MovieMarker="MARK43" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[comments.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:10]]></Time>
<TimeTick>1293047290</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="123" MovieMarker="MARK44" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="86" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_8]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_9]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:11]]></Time>
<TimeTick>1293047291</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[You have successfully.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:11]]></Time>
<TimeTick>1293047291</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="126" MovieMarker="MARK45" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[You have successfully.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[ModelCharacteristics]]></Obj>
<Details ><![CDATA[Model '150067374' model characteristics modified and system displayed a message 'You have successfully edited the Model Characteristics. '.]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:11]]></Time>
<TimeTick>1293047291</TimeTick>
<NodeArgs eType="User" icon="7" nRep="128" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ModelCharacteristics]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="125" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_9]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/22/2010 - 14:48:02" eTime="12/22/2010 - 14:48:11" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" MovieMarker="MARK15" >
<Disp><![CDATA[ModelCharacteristics Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Admin Modify Model Characteristics Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T59" iterID="2" >
<Action rID="T60">
<AName><![CDATA[ModelCharacteristics]]></AName>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:12]]></Time>
<TimeTick>1293047292</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:12]]></Time>
<TimeTick>1293047292</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:12]]></Time>
<TimeTick>1293047292</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="136" MovieMarker="MARK47" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[ModelCharacteristics]]></Obj>
<Details ><![CDATA[caMOD application page opened.]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:12]]></Time>
<TimeTick>1293047292</TimeTick>
<NodeArgs eType="User" icon="7" nRep="137" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ModelCharacteristics]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="135" status="Passed" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:12]]></Time>
<TimeTick>1293047292</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[ADMINISTRATION.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:12]]></Time>
<TimeTick>1293047292</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="140" MovieMarker="MARK48" Source="ModelCharacteristics" SourceLine="-1" >
<Disp><![CDATA[ADMINISTRATION.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:48:12]]></Time>
<TimeTick>1293047292</TimeTick>