<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[H:\KambampatiM\Automation\caMOD\View Model Assignment]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[View Model Assignment]]></DName>
<Res><![CDATA[Res22]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[QueryModelsAssignment]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:50]]></Time>
<TimeTick>1293038750</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:50]]></Time>
<TimeTick>1293038750</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[ADMIN.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:50]]></Time>
<TimeTick>1293038750</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" MovieMarker="MARK104" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[QueryModelsAssignment]]></Obj>
<Details ><![CDATA[User logged into caMOD application with Administrator account.]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:50]]></Time>
<TimeTick>1293038750</TimeTick>
<NodeArgs eType="User" icon="8" nRep="12" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryModelsAssignment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:50]]></Time>
<TimeTick>1293038750</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" MovieMarker="MARK105" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:51]]></Time>
<TimeTick>1293038751</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:51]]></Time>
<TimeTick>1293038751</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" MovieMarker="MARK106" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="18" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:52]]></Time>
<TimeTick>1293038752</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:52]]></Time>
<TimeTick>1293038752</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" MovieMarker="MARK107" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:52]]></Time>
<TimeTick>1293038752</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="29" MovieMarker="MARK108" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:58]]></Time>
<TimeTick>1293038758</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="31" MovieMarker="MARK109" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[QA Test Model.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:58]]></Time>
<TimeTick>1293038758</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="33" MovieMarker="MARK110" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QA Test Model.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:58]]></Time>
<TimeTick>1293038758</TimeTick>
<NodeArgs eType="General" icon="11" nRep="35" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[QueryModelsAssignment]]></Obj>
<Details ><![CDATA[Models Assignment query for '' status results are 'Your search returned 1,062 records'.]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:58]]></Time>
<TimeTick>1293038758</TimeTick>
<NodeArgs eType="User" icon="8" nRep="36" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryModelsAssignment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:58]]></Time>
<TimeTick>1293038758</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:58]]></Time>
<TimeTick>1293038758</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" MovieMarker="MARK111" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="39" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:59]]></Time>
<TimeTick>1293038759</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Incomplete"]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:59]]></Time>
<TimeTick>1293038759</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" MovieMarker="MARK112" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:25:59]]></Time>
<TimeTick>1293038759</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" MovieMarker="MARK113" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:02]]></Time>
<TimeTick>1293038762</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="51" MovieMarker="MARK114" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[QA Test Model.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:02]]></Time>
<TimeTick>1293038762</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="53" MovieMarker="MARK115" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QA Test Model.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:02]]></Time>
<TimeTick>1293038762</TimeTick>
<NodeArgs eType="General" icon="11" nRep="55" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[QueryModelsAssignment]]></Obj>
<Details ><![CDATA[Models Assignment query for 'Incomplete' status results are 'Your search returned 16 records'.]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:02]]></Time>
<TimeTick>1293038762</TimeTick>
<NodeArgs eType="User" icon="8" nRep="56" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryModelsAssignment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="45" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:02]]></Time>
<TimeTick>1293038762</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:02]]></Time>
<TimeTick>1293038762</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" MovieMarker="MARK116" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="59" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:03]]></Time>
<TimeTick>1293038763</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Complete-not screened"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:03]]></Time>
<TimeTick>1293038763</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="66" MovieMarker="MARK117" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:03]]></Time>
<TimeTick>1293038763</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" MovieMarker="MARK118" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="71" MovieMarker="MARK119" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[QA Test Model.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="73" MovieMarker="MARK120" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QA Test Model.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<NodeArgs eType="General" icon="11" nRep="75" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[QueryModelsAssignment]]></Obj>
<Details ><![CDATA[Models Assignment query for 'Complete-not screened' status results are 'Your search returned 17 records'.]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<NodeArgs eType="User" icon="8" nRep="76" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryModelsAssignment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="65" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="80" MovieMarker="MARK121" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="79" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Screener-assigned"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:06]]></Time>
<TimeTick>1293038766</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="86" MovieMarker="MARK122" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:07]]></Time>
<TimeTick>1293038767</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="89" MovieMarker="MARK123" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:07]]></Time>
<TimeTick>1293038767</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="91" MovieMarker="MARK124" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[QA Test Model.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:27]]></Time>
<TimeTick>1293038787</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="288" MovieMarker="MARK125" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QA Test Model.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[QueryModelsAssignment]]></Obj>
<Details ><![CDATA[Search results NOT displayed for 'Incomplete' status.]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:27]]></Time>
<TimeTick>1293038787</TimeTick>
<NodeArgs eType="User" icon="8" nRep="289" status="Warning" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryModelsAssignment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="85" status="Warning" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:27]]></Time>
<TimeTick>1293038787</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:27]]></Time>
<TimeTick>1293038787</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="293" MovieMarker="MARK126" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="292" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:28]]></Time>
<TimeTick>1293038788</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Screened-approved"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:28]]></Time>
<TimeTick>1293038788</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="299" MovieMarker="MARK127" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:28]]></Time>
<TimeTick>1293038788</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="302" MovieMarker="MARK128" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:28]]></Time>
<TimeTick>1293038788</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="304" MovieMarker="MARK129" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[QA Test Model.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:49]]></Time>
<TimeTick>1293038809</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="501" MovieMarker="MARK130" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QA Test Model.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[QueryModelsAssignment]]></Obj>
<Details ><![CDATA[Search results NOT displayed for 'Incomplete' status.]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:49]]></Time>
<TimeTick>1293038809</TimeTick>
<NodeArgs eType="User" icon="8" nRep="502" status="Warning" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryModelsAssignment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="298" status="Warning" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:49]]></Time>
<TimeTick>1293038809</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:49]]></Time>
<TimeTick>1293038809</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="506" MovieMarker="MARK131" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="505" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:50]]></Time>
<TimeTick>1293038810</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Screened-rejected"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:50]]></Time>
<TimeTick>1293038810</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="512" MovieMarker="MARK132" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:50]]></Time>
<TimeTick>1293038810</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="515" MovieMarker="MARK133" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="517" MovieMarker="MARK134" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[QA Test Model.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="519" MovieMarker="MARK135" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QA Test Model.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<NodeArgs eType="General" icon="11" nRep="521" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[QueryModelsAssignment]]></Obj>
<Details ><![CDATA[Models Assignment query for 'Screened-rejected' status results are 'Your search returned 20 records'.]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<NodeArgs eType="User" icon="8" nRep="522" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryModelsAssignment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="511" status="Passed" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="526" MovieMarker="MARK136" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW MODEL ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="525" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Editor-assigned"]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="532" MovieMarker="MARK137" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 12:26:53]]></Time>
<TimeTick>1293038813</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="535" MovieMarker="MARK138" Source="QueryModelsAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>