<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[H:\KambampatiM\Automation\caMOD\View Comment Assignment]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[View Comment Assignment]]></DName>
<Res><![CDATA[Res24]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[QueryCommentAssignment]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:51]]></Time>
<TimeTick>1293045231</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:51]]></Time>
<TimeTick>1293045231</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[ADMIN.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:51]]></Time>
<TimeTick>1293045231</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" MovieMarker="MARK40" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[QueryCommentAssignment]]></Obj>
<Details ><![CDATA[User logged into caMOD application with Administrator account.]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:51]]></Time>
<TimeTick>1293045231</TimeTick>
<NodeArgs eType="User" icon="8" nRep="12" status="Passed" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryCommentAssignment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" status="Passed" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:51]]></Time>
<TimeTick>1293045231</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:51]]></Time>
<TimeTick>1293045231</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" MovieMarker="MARK41" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:52]]></Time>
<TimeTick>1293045232</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:52]]></Time>
<TimeTick>1293045232</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" MovieMarker="MARK42" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:52]]></Time>
<TimeTick>1293045232</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:52]]></Time>
<TimeTick>1293045232</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" MovieMarker="MARK43" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:52]]></Time>
<TimeTick>1293045232</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" MovieMarker="MARK44" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:13:53]]></Time>
<TimeTick>1293045233</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" MovieMarker="MARK45" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Genetic Description Page.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:13]]></Time>
<TimeTick>1293045253</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="228" MovieMarker="MARK46" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Genetic Description Page.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[QueryCommentAssignment]]></Obj>
<Details ><![CDATA[Search results NOT displayed for ''.]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:13]]></Time>
<TimeTick>1293045253</TimeTick>
<NodeArgs eType="User" icon="8" nRep="229" status="Warning" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryCommentAssignment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:13]]></Time>
<TimeTick>1293045253</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="232" MovieMarker="MARK47" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Complete-not screened"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:14]]></Time>
<TimeTick>1293045254</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="237" MovieMarker="MARK48" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:14]]></Time>
<TimeTick>1293045254</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="240" MovieMarker="MARK49" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:15]]></Time>
<TimeTick>1293045255</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="242" MovieMarker="MARK50" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Genetic Description Page.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:15]]></Time>
<TimeTick>1293045255</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="244" MovieMarker="MARK51" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Genetic Description Page.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:15]]></Time>
<TimeTick>1293045255</TimeTick>
<NodeArgs eType="General" icon="11" nRep="246" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[QueryCommentAssignment]]></Obj>
<Details ><![CDATA[Comment Assignment query for 'Complete-not screened' results are 'Your search returned 3 records'.]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:15]]></Time>
<TimeTick>1293045255</TimeTick>
<NodeArgs eType="User" icon="8" nRep="247" status="Passed" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryCommentAssignment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:15]]></Time>
<TimeTick>1293045255</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="250" MovieMarker="MARK52" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Screener-assigned"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:16]]></Time>
<TimeTick>1293045256</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="255" MovieMarker="MARK53" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:16]]></Time>
<TimeTick>1293045256</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="258" MovieMarker="MARK54" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:16]]></Time>
<TimeTick>1293045256</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="260" MovieMarker="MARK55" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Genetic Description Page.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:37]]></Time>
<TimeTick>1293045277</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="453" MovieMarker="MARK56" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Genetic Description Page.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[QueryCommentAssignment]]></Obj>
<Details ><![CDATA[Search results NOT displayed for 'Screener-assigned'.]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:37]]></Time>
<TimeTick>1293045277</TimeTick>
<NodeArgs eType="User" icon="8" nRep="454" status="Warning" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryCommentAssignment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:37]]></Time>
<TimeTick>1293045277</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="457" MovieMarker="MARK57" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Screened-approved"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:37]]></Time>
<TimeTick>1293045277</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="462" MovieMarker="MARK58" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:37]]></Time>
<TimeTick>1293045277</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="465" MovieMarker="MARK59" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:38]]></Time>
<TimeTick>1293045278</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="467" MovieMarker="MARK60" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Genetic Description Page.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:58]]></Time>
<TimeTick>1293045298</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="665" MovieMarker="MARK61" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Genetic Description Page.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[QueryCommentAssignment]]></Obj>
<Details ><![CDATA[Search results NOT displayed for 'Screened-approved'.]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:58]]></Time>
<TimeTick>1293045298</TimeTick>
<NodeArgs eType="User" icon="8" nRep="666" status="Warning" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryCommentAssignment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:58]]></Time>
<TimeTick>1293045298</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="669" MovieMarker="MARK62" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[currentState.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Screened-rejected"]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:59]]></Time>
<TimeTick>1293045299</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="674" MovieMarker="MARK63" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[currentState.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:14:59]]></Time>
<TimeTick>1293045299</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="677" MovieMarker="MARK64" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:15:02]]></Time>
<TimeTick>1293045302</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="679" MovieMarker="MARK65" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Genetic Description Page.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 14:15:02]]></Time>
<TimeTick>1293045302</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="681" MovieMarker="MARK66" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[Genetic Description Page.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 14:15:02]]></Time>
<TimeTick>1293045302</TimeTick>
<NodeArgs eType="General" icon="11" nRep="683" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[QueryCommentAssignment]]></Obj>
<Details ><![CDATA[Comment Assignment query for 'Screened-rejected' results are 'Your search returned 16 records'.]]></Details>
<Time><![CDATA[12/22/2010 - 14:15:02]]></Time>
<TimeTick>1293045302</TimeTick>
<NodeArgs eType="User" icon="8" nRep="684" status="Passed" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[QueryCommentAssignment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:15:02]]></Time>
<TimeTick>1293045302</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="687" MovieMarker="MARK67" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[VIEW COMMENT ASSIGNMENT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 14:15:05]]></Time>
<TimeTick>1293045305</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="690" MovieMarker="MARK68" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" status="Warning" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" status="Warning" Source="QueryCommentAssignment" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/22/2010 - 14:13:51" eTime="12/22/2010 - 14:15:05" passed="3" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" MovieMarker="MARK39" >
<Disp><![CDATA[QueryCommentAssignment Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[View Comment Assignment Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="12/22/2010 - 14:13:49" eTime="12/22/2010 - 14:15:05" passed="3" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test View Comment Assignment Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>