=== CBIIT/camod-docs/artifacts/TODO/camod_dev.war/config/CurationConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="curationStatesType">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="state" type="stateType" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="actionsType">
		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="action" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="nextValidStateType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="match-event" type="xsd:string" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="nextValidStatesType">
		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="next-valid-state" type="nextValidStateType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="stateType" >
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="actions" type="actionsType" minOccurs="0" maxOccurs="1" />
			<xsd:element name="next-valid-states" type="nextValidStatesType" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="default" type="xsd:boolean" />
	</xsd:complexType>

    <xsd:element name="curation-states" type="curationStatesType" />
</xsd:schema>

=== CBIIT/camod-docs/Configuration/HowTos/Nick/jboss-4.0.2/server/default/deploy/camod_dev.war/config/CurationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<curation-states xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost/camod/config/CurationConfig.xsd" >
	<state default="true">
	 	<name>Incomplete</name>
		<next-valid-states>
		    <next-valid-state>
		        <name>Complete-not screened</name>
		        <match-event>complete</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>			    
		</next-valid-states>
	</state>
	
	<state default="false">
	 	<name>Complete-not screened</name>
	    <actions>
		    <action>emailAssignee</action>
		</actions>
		<next-valid-states>
		    <next-valid-state>
		        <name>Screener-assigned</name>
		        <match-event>assign_screener</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>			    
		</next-valid-states>
	</state>
	
	<state default="false">
	 	<name>Screener-assigned</name>
	    <actions>
		    <action>emailAssignee</action>
		</actions>
		<next-valid-states>
		    <next-valid-state>
		        <name>Screened-approved</name>
		        <match-event>screener_approve</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Screened-rejected</name>
		        <match-event>screener_reject</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>				    
		</next-valid-states>	
	</state>
	
	<state default="false">
	 	<name>Screened-approved</name>
	    <actions>
		    <action>emailAssignee</action>
		</actions>
		<next-valid-states>
		    <next-valid-state>
		        <name>Editor-assigned</name>
		        <match-event>assign_editor</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>			    
		</next-valid-states>
	</state>
	
	<state default="false">
	 	<name>Screened-rejected</name>
		<next-valid-states>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>			    		    
		</next-valid-states>	 	
	</state>
	
	<state default="false">
	 	<name>Editor-assigned</name>
		<actions>
		    <action>emailAssignee</action>
		</actions>
		<next-valid-states>
		    <next-valid-state>
		        <name>Edited-approved</name>
		        <match-event>editor_approve</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Edited-need more info</name>
		        <match-event>need_more_info</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>			    
		</next-valid-states>
	</state>
	
	<state default="false">
	 	<name>Edited-approved</name>
		<next-valid-states>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>			    		    
		</next-valid-states>			 	
	</state>
	
	<state default="false">
	 	<name>Edited-need more info</name>
		<actions>
		    <action>emailAssignee</action>
		</actions>
		<next-valid-states>
		    <next-valid-state>
		        <name>Edited-approved</name>
		        <match-event>editor_approve</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Edited-need more info</name>
		        <match-event>need_more_info</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Inactive</name>
		        <match-event>inactivate</match-event>
		    </next-valid-state>			    		    
		</next-valid-states>
	</state>
	
	<state default="false">
	 	<name>Inactive</name>
		<next-valid-states>
		    <next-valid-state>
		        <name>Complete-not screened</name>
		        <match-event>complete</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Screened-approved</name>
		        <match-event>screener_approve</match-event>
		    </next-valid-state>		    
		</next-valid-states>	 		 	
	</state>	
</curation-states>

=== CBIIT/camod-docs/artifacts/TODO/camod_dev.war/config/CommentCurationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<curation-states xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost/camod/config/CurationConfig.xsd" >
	<state default="true">
	 	<name>Complete-not screened</name>
	    <actions>
		    <action>emailAssignee</action>
		</actions>
		<next-valid-states>
		    <next-valid-state>
		        <name>Screener-assigned</name>
		        <match-event>assign_screener</match-event>
		    </next-valid-state>
		</next-valid-states>
	</state>
	
	<state default="false">
	 	<name>Screener-assigned</name>
	    <actions>
		    <action>emailAssignee</action>
		</actions>
		<next-valid-states>
		    <next-valid-state>
		        <name>Screened-approved</name>
		        <match-event>screener_approve</match-event>
		    </next-valid-state>
		    <next-valid-state>
		        <name>Screened-rejected</name>
		        <match-event>screener_reject</match-event>
		    </next-valid-state>
		</next-valid-states>
	</state>
	
	<state default="false">
	 	<name>Screened-approved</name>
	</state>
	
	<state default="false">
	 	<name>Screened-rejected</name>
	</state>
</curation-states>
