<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[H:\KambampatiM\Automation\caMOD\Role Management]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Role Management]]></DName>
<Res><![CDATA[Res24]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[UserRoleSelection]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:58]]></Time>
<TimeTick>1294165918</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:58]]></Time>
<TimeTick>1294165918</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[ADMIN.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:58]]></Time>
<TimeTick>1294165918</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" MovieMarker="MARK1" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("ADMIN")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[UserRoleSelection]]></Obj>
<Details ><![CDATA[User logged into caMOD application with Administrator account.]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:58]]></Time>
<TimeTick>1294165918</TimeTick>
<NodeArgs eType="User" icon="8" nRep="12" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[UserRoleSelection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:58]]></Time>
<TimeTick>1294165918</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" MovieMarker="MARK2" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("ADMIN")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ROLE MANAGEMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:58]]></Time>
<TimeTick>1294165918</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" MovieMarker="MARK3" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ROLE MANAGEMENT.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("ROLE MANAGEMENT")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:59]]></Time>
<TimeTick>1294165919</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[currentRole.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["All"]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:59]]></Time>
<TimeTick>1294165919</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" MovieMarker="MARK4" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[currentRole.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebList("currentRole")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:31:59]]></Time>
<TimeTick>1294165919</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" MovieMarker="MARK5" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebButton("Submit")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:06]]></Time>
<TimeTick>1294165926</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" MovieMarker="MARK6" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[userName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:06]]></Time>
<TimeTick>1294165926</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="32" MovieMarker="MARK7" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[userName.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebElement("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:06]]></Time>
<TimeTick>1294165926</TimeTick>
<NodeArgs eType="General" icon="11" nRep="34" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[UserRoleSelection]]></Obj>
<Details ><![CDATA[User queried for role 'All'.
Returned results are 'Your search returned 1,102 records'.]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:11]]></Time>
<TimeTick>1294165931</TimeTick>
<NodeArgs eType="User" icon="8" nRep="35" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[UserRoleSelection]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:11]]></Time>
<TimeTick>1294165931</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[ROLE MANAGEMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:11]]></Time>
<TimeTick>1294165931</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" MovieMarker="MARK8" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ROLE MANAGEMENT.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("ROLE MANAGEMENT")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:12]]></Time>
<TimeTick>1294165932</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[currentRole.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["MMHCC Coordinator"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:12]]></Time>
<TimeTick>1294165932</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" MovieMarker="MARK9" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[currentRole.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebList("currentRole")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:12]]></Time>
<TimeTick>1294165932</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="48" MovieMarker="MARK10" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebButton("Submit")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:18]]></Time>
<TimeTick>1294165938</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="50" MovieMarker="MARK11" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[userName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:18]]></Time>
<TimeTick>1294165938</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="52" MovieMarker="MARK12" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[userName.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebElement("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:18]]></Time>
<TimeTick>1294165938</TimeTick>
<NodeArgs eType="General" icon="11" nRep="54" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[UserRoleSelection]]></Obj>
<Details ><![CDATA[User queried for role 'MMHCC Coordinator'.
Returned results are 'Your search returned 24 records'.]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:20]]></Time>
<TimeTick>1294165940</TimeTick>
<NodeArgs eType="User" icon="8" nRep="55" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[UserRoleSelection]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="44" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:20]]></Time>
<TimeTick>1294165940</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[ROLE MANAGEMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:20]]></Time>
<TimeTick>1294165940</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="59" MovieMarker="MARK13" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ROLE MANAGEMENT.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("ROLE MANAGEMENT")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:21]]></Time>
<TimeTick>1294165941</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[currentRole.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["MMHCC Editor"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:21]]></Time>
<TimeTick>1294165941</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" MovieMarker="MARK14" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[currentRole.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebList("currentRole")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:21]]></Time>
<TimeTick>1294165941</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="68" MovieMarker="MARK15" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebButton("Submit")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:25]]></Time>
<TimeTick>1294165945</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="70" MovieMarker="MARK16" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[userName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:25]]></Time>
<TimeTick>1294165945</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="72" MovieMarker="MARK17" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[userName.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf25.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebElement("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:25]]></Time>
<TimeTick>1294165945</TimeTick>
<NodeArgs eType="General" icon="11" nRep="74" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf26.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[UserRoleSelection]]></Obj>
<Details ><![CDATA[User queried for role 'MMHCC Editor'.
Returned results are 'Your search returned 12 records'.]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:27]]></Time>
<TimeTick>1294165947</TimeTick>
<NodeArgs eType="User" icon="8" nRep="75" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[UserRoleSelection]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="64" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:27]]></Time>
<TimeTick>1294165947</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[ROLE MANAGEMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:27]]></Time>
<TimeTick>1294165947</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" MovieMarker="MARK18" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ROLE MANAGEMENT.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf28.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("ROLE MANAGEMENT")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="78" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf27.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:28]]></Time>
<TimeTick>1294165948</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[currentRole.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["MMHCC Screener"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:28]]></Time>
<TimeTick>1294165948</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="85" MovieMarker="MARK19" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[currentRole.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf30.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebList("currentRole")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:28]]></Time>
<TimeTick>1294165948</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="88" MovieMarker="MARK20" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf31.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebButton("Submit")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Your search returned.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:31]]></Time>
<TimeTick>1294165951</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="90" MovieMarker="MARK21" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[Your search returned.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf32.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[userName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:31]]></Time>
<TimeTick>1294165951</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="92" MovieMarker="MARK22" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[userName.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf33.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebElement("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["Your search returned":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:31]]></Time>
<TimeTick>1294165951</TimeTick>
<NodeArgs eType="General" icon="11" nRep="94" >
<Disp><![CDATA["Your search returned":Function Call]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf34.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").WebTable("Your search returned")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[UserRoleSelection]]></Obj>
<Details ><![CDATA[User queried for role 'MMHCC Screener'.
Returned results are 'Your search returned 5 records'.]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:32]]></Time>
<TimeTick>1294165952</TimeTick>
<NodeArgs eType="User" icon="8" nRep="95" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[UserRoleSelection]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="84" status="Passed" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf29.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:32]]></Time>
<TimeTick>1294165952</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[ROLE MANAGEMENT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:32]]></Time>
<TimeTick>1294165952</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="99" MovieMarker="MARK23" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ROLE MANAGEMENT.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf36.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("ROLE MANAGEMENT")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="98" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf35.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:33]]></Time>
<TimeTick>1294165953</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:32:33]]></Time>
<TimeTick>1294165953</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="103" MovieMarker="MARK24" Source="UserRoleSelection" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf38.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").Link("ADMIN")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>