<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[C:\SVNatNCI_old\PEDAL_QTP\tst\ST_Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[ST_Driver]]></DName>
<Res><![CDATA[Res18]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:05]]></Time>
<TimeTick>1294164485</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:05]]></Time>
<TimeTick>1294164485</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SEARCH MODELS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:05]]></Time>
<TimeTick>1294164485</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" MovieMarker="MARK68" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SEARCH MODELS.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf97.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("SEARCH MODELS")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf96.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:06]]></Time>
<TimeTick>1294164486</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:06]]></Time>
<TimeTick>1294164486</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" MovieMarker="MARK69" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf99.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf98.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:07]]></Time>
<TimeTick>1294164487</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:07]]></Time>
<TimeTick>1294164487</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" MovieMarker="MARK70" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf101.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[cellLine.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["ANV"]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:08]]></Time>
<TimeTick>1294164488</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" MovieMarker="MARK71" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[cellLine.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf102.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebList("cellLine")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:08]]></Time>
<TimeTick>1294164488</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" MovieMarker="MARK72" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf103.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Unique Model Identifier_33]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test13.xls
Row: 7
Expected value: 
343
Matched actual value: 
343]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:08]]></Time>
<TimeTick>1294164488</TimeTick>
<NodeArgs eType="User" icon="9" nRep="27" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_33]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="18" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf100.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_3")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:08]]></Time>
<TimeTick>1294164488</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:08]]></Time>
<TimeTick>1294164488</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" MovieMarker="MARK73" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf105.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 4").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf104.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_4")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:09]]></Time>
<TimeTick>1294164489</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:09]]></Time>
<TimeTick>1294164489</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" MovieMarker="MARK74" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf107.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[searchTherapeuticApproaches.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:10]]></Time>
<TimeTick>1294164490</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="38" MovieMarker="MARK75" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[searchTherapeuticApproaches.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf108.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebCheckBox("searchTherapeuticApproaches")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:10]]></Time>
<TimeTick>1294164490</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" MovieMarker="MARK76" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf109.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Unique Model Identifier_34]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test13.xls
Row: 12
Expected value: 
10
Matched actual value: 
10]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:13]]></Time>
<TimeTick>1294164493</TimeTick>
<NodeArgs eType="User" icon="9" nRep="43" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_34]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="34" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf106.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_3")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:13]]></Time>
<TimeTick>1294164493</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:13]]></Time>
<TimeTick>1294164493</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" MovieMarker="MARK77" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf111.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 4").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf110.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_4")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:13]]></Time>
<TimeTick>1294164493</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:13]]></Time>
<TimeTick>1294164493</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" MovieMarker="MARK78" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf113.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[searchTherapeuticApproaches.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:14]]></Time>
<TimeTick>1294164494</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="54" MovieMarker="MARK79" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[searchTherapeuticApproaches.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf114.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebCheckBox("searchTherapeuticApproaches")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[therapeuticApproachCompoundDrug.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["alpha-interferon"]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:14]]></Time>
<TimeTick>1294164494</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" MovieMarker="MARK80" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[therapeuticApproachCompoundDrug.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf115.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebList("therapeuticApproachCompoundDrug")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:14]]></Time>
<TimeTick>1294164494</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" MovieMarker="MARK81" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf116.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Unique Model Identifier_35]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test13.xls
Row: 18
Expected value: 
228
Matched actual value: 
228]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:15]]></Time>
<TimeTick>1294164495</TimeTick>
<NodeArgs eType="User" icon="9" nRep="62" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_35]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Test Case elapsed Time]]></Obj>
<Details ><![CDATA[TestCaseElapsedTime: 14.272seconds]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:15]]></Time>
<TimeTick>1294164495</TimeTick>
<NodeArgs eType="User" icon="9" nRep="63" status="Information" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Test Case elapsed Time]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30" retval=" ">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/4/2011 - 13:08:16]]></Time>
<TimeTick>1294164496</TimeTick>
<NodeArgs eType="General" icon="11" nRep="64" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="50" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf112.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_3")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/4/2011 - 13:07:51" eTime="1/4/2011 - 13:08:16" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" MovieMarker="MARK67" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="1/4/2011 - 13:07:49" eTime="1/4/2011 - 13:08:16" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test ST_Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>