<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[H:\KambampatiM\Automation\caMOD\Admin Modify Genetic Description_test1]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Admin Modify Genetic Description_test1]]></DName>
<Res><![CDATA[Res28]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Transgene]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:21]]></Time>
<TimeTick>1293048021</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:21]]></Time>
<TimeTick>1293048021</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:21]]></Time>
<TimeTick>1293048021</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" MovieMarker="MARK1" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Transgene]]></Obj>
<Details ><![CDATA[caMOD application page opened.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:21]]></Time>
<TimeTick>1293048021</TimeTick>
<NodeArgs eType="User" icon="7" nRep="12" status="Passed" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[Transgene]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" status="Passed" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:21]]></Time>
<TimeTick>1293048021</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ADMINISTRATION.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:21]]></Time>
<TimeTick>1293048021</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" MovieMarker="MARK2" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[ADMINISTRATION.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:21]]></Time>
<TimeTick>1293048021</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" MovieMarker="MARK3" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="20" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="22" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="24" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="26" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="28" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="30" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="32" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="34" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="36" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["ADMINISTRATION":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="General" icon="8" nRep="38" >
<Disp><![CDATA["ADMINISTRATION":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Transgene]]></Obj>
<Details ><![CDATA[User logged into caMOD with SuperUser role.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="User" icon="7" nRep="39" status="Passed" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[Transgene]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[ADMIN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:22]]></Time>
<TimeTick>1293048022</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="42" MovieMarker="MARK4" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[ADMIN.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" status="Passed" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:23]]></Time>
<TimeTick>1293048023</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[EDIT MODELS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:23]]></Time>
<TimeTick>1293048023</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" MovieMarker="MARK5" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[EDIT MODELS.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="45" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:24]]></Time>
<TimeTick>1293048024</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:24]]></Time>
<TimeTick>1293048024</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" MovieMarker="MARK6" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[modelId.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["150067374"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:24]]></Time>
<TimeTick>1293048024</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="53" MovieMarker="MARK7" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[modelId.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Search by Model Id.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:24]]></Time>
<TimeTick>1293048024</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="56" MovieMarker="MARK8" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[Search by Model Id.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["No."- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (19 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebTable<br>html tag=TABLE<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (19 objects found)&nbsp;</FONT></u><br>
micclass=WebTable<br>html tag=TABLE<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=row<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>border=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:25]]></Time>
<TimeTick>1293048025</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="58" MovieMarker="MARK9" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA["No."- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["No.":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:25]]></Time>
<TimeTick>1293048025</TimeTick>
<NodeArgs eType="General" icon="8" nRep="59" >
<Disp><![CDATA["No.":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Model_10082010 Modified  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:25]]></Time>
<TimeTick>1293048025</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="62" MovieMarker="MARK10" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[[ Model_10082010 Modified  ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="49" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_5]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:26]]></Time>
<TimeTick>1293048026</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[GENETIC DESCRIPTION.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:26]]></Time>
<TimeTick>1293048026</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="66" MovieMarker="MARK11" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[GENETIC DESCRIPTION.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Enter Transgene.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:26]]></Time>
<TimeTick>1293048026</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" MovieMarker="MARK12" Source="Transgene" SourceLine="-1" >
<Disp><![CDATA[Enter Transgene.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details ><![CDATA[There are '6' list boxes found in page 'caMOD - Cancer Models.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="User" icon="7" nRep="71" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ scientificName ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Cattle (Bos taurus)"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="74" MovieMarker="MARK13" >
<Disp><![CDATA[[ scientificName ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[scientificName]]></Obj>
<Details ><![CDATA[List box 'scientificName' entered with Cattle (Bos taurus).]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="User" icon="7" nRep="75" status="Passed" >
<Disp><![CDATA[scientificName]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ transcriptional1_species ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Cattle (Bos taurus)"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="78" MovieMarker="MARK14" >
<Disp><![CDATA[[ transcriptional1_species ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[transcriptional1_species]]></Obj>
<Details ><![CDATA[List box 'transcriptional1_species' entered with Cattle (Bos taurus).]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="User" icon="7" nRep="79" status="Passed" >
<Disp><![CDATA[transcriptional1_species]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ transcriptional2_species ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Cattle (Bos taurus)"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="82" MovieMarker="MARK15" >
<Disp><![CDATA[[ transcriptional2_species ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[transcriptional2_species]]></Obj>
<Details ><![CDATA[List box 'transcriptional2_species' entered with Cattle (Bos taurus).]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="User" icon="7" nRep="83" status="Passed" >
<Disp><![CDATA[transcriptional2_species]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ transcriptional3_species ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Cattle (Bos taurus)"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="86" MovieMarker="MARK16" >
<Disp><![CDATA[[ transcriptional3_species ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[transcriptional3_species]]></Obj>
<Details ><![CDATA[List box 'transcriptional3_species' entered with Cattle (Bos taurus).]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:27]]></Time>
<TimeTick>1293048027</TimeTick>
<NodeArgs eType="User" icon="7" nRep="87" status="Passed" >
<Disp><![CDATA[transcriptional3_species]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ polyASignal_species ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Cattle (Bos taurus)"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="90" MovieMarker="MARK17" >
<Disp><![CDATA[[ polyASignal_species ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[polyASignal_species]]></Obj>
<Details ><![CDATA[List box 'polyASignal_species' entered with Cattle (Bos taurus).]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="User" icon="7" nRep="91" status="Passed" >
<Disp><![CDATA[polyASignal_species]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ spliceSites_species ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Cattle (Bos taurus)"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="94" MovieMarker="MARK18" >
<Disp><![CDATA[[ spliceSites_species ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[spliceSites_species]]></Obj>
<Details ><![CDATA[List box 'spliceSites_species' entered with Cattle (Bos taurus).]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="User" icon="7" nRep="95" status="Passed" >
<Disp><![CDATA[spliceSites_species]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details ><![CDATA[There are '20' edit boxes found in page 'caMOD - Cancer Models.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="User" icon="7" nRep="97" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ locationOfIntegration ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment1"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="99" MovieMarker="MARK19" >
<Disp><![CDATA[[ locationOfIntegration ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[locationOfIntegration]]></Obj>
<Details ><![CDATA[Edit box 'locationOfIntegration' entered with .]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="User" icon="7" nRep="100" status="Passed" >
<Disp><![CDATA[locationOfIntegration]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ name ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment2"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="102" MovieMarker="MARK20" >
<Disp><![CDATA[[ name ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[name]]></Obj>
<Details ><![CDATA[Edit box 'name' entered with .]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="User" icon="7" nRep="103" status="Passed" >
<Disp><![CDATA[name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[otherScientificName]]></Obj>
<Details ><![CDATA[Edit box 'otherScientificName' disabled.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:28]]></Time>
<TimeTick>1293048028</TimeTick>
<NodeArgs eType="User" icon="7" nRep="104" status="Warning" >
<Disp><![CDATA[otherScientificName]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ transcriptional1_name ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment4"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="106" MovieMarker="MARK21" >
<Disp><![CDATA[[ transcriptional1_name ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[transcriptional1_name]]></Obj>
<Details ><![CDATA[Edit box 'transcriptional1_name' entered with .]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="107" status="Passed" >
<Disp><![CDATA[transcriptional1_name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[transcriptional1_otherSpecies]]></Obj>
<Details ><![CDATA[Edit box 'transcriptional1_otherSpecies' disabled.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="108" status="Warning" >
<Disp><![CDATA[transcriptional1_otherSpecies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ transcriptional2_name ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment6"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="110" MovieMarker="MARK22" >
<Disp><![CDATA[[ transcriptional2_name ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[transcriptional2_name]]></Obj>
<Details ><![CDATA[Edit box 'transcriptional2_name' entered with .]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="111" status="Passed" >
<Disp><![CDATA[transcriptional2_name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[transcriptional2_otherSpecies]]></Obj>
<Details ><![CDATA[Edit box 'transcriptional2_otherSpecies' disabled.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="112" status="Warning" >
<Disp><![CDATA[transcriptional2_otherSpecies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ transcriptional3_name ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment8"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="114" MovieMarker="MARK23" >
<Disp><![CDATA[[ transcriptional3_name ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[transcriptional3_name]]></Obj>
<Details ><![CDATA[Edit box 'transcriptional3_name' entered with .]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="115" status="Passed" >
<Disp><![CDATA[transcriptional3_name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[transcriptional3_otherSpecies]]></Obj>
<Details ><![CDATA[Edit box 'transcriptional3_otherSpecies' disabled.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="116" status="Warning" >
<Disp><![CDATA[transcriptional3_otherSpecies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ polyASignal_name ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment10"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="118" MovieMarker="MARK24" >
<Disp><![CDATA[[ polyASignal_name ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA[polyASignal_name]]></Obj>
<Details ><![CDATA[Edit box 'polyASignal_name' entered with .]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="119" status="Passed" >
<Disp><![CDATA[polyASignal_name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[polyASignal_otherSpecies]]></Obj>
<Details ><![CDATA[Edit box 'polyASignal_otherSpecies' disabled.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="120" status="Warning" >
<Disp><![CDATA[polyASignal_otherSpecies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ spliceSites_name ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment12"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="122" MovieMarker="MARK25" >
<Disp><![CDATA[[ spliceSites_name ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[spliceSites_name]]></Obj>
<Details ><![CDATA[Edit box 'spliceSites_name' entered with .]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="123" status="Passed" >
<Disp><![CDATA[spliceSites_name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj ><![CDATA[spliceSites_otherSpecies]]></Obj>
<Details ><![CDATA[Edit box 'spliceSites_otherSpecies' disabled.]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:29]]></Time>
<TimeTick>1293048029</TimeTick>
<NodeArgs eType="User" icon="7" nRep="124" status="Warning" >
<Disp><![CDATA[spliceSites_otherSpecies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ geneFunctions ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Auto Test Comment14"]]></Details>
<Time><![CDATA[12/22/2010 - 15:00:30]]></Time>
<TimeTick>1293048030</TimeTick>