<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CBIIT-QAPC0"><DocLocation><![CDATA[C:\SVNatNCI_old\PEDAL_QTP\tst\ST_Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[ST_Driver]]></DName>
<Res><![CDATA[Res21]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:41]]></Time>
<TimeTick>1294164881</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:41]]></Time>
<TimeTick>1294164881</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SEARCH MODELS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:41]]></Time>
<TimeTick>1294164881</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" MovieMarker="MARK114" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SEARCH MODELS.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf161.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models").Link("SEARCH MODELS")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf160.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:42]]></Time>
<TimeTick>1294164882</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:42]]></Time>
<TimeTick>1294164882</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" MovieMarker="MARK115" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf163.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 2").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf162.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:43]]></Time>
<TimeTick>1294164883</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:43]]></Time>
<TimeTick>1294164883</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" MovieMarker="MARK116" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf165.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[species.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Rabbit (Oryctolagus cuniculus)"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:44]]></Time>
<TimeTick>1294164884</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" MovieMarker="MARK117" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[species.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf166.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebList("species")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[searchTherapeuticApproaches.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:44]]></Time>
<TimeTick>1294164884</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" MovieMarker="MARK118" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[searchTherapeuticApproaches.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf167.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebCheckBox("searchTherapeuticApproaches")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:44]]></Time>
<TimeTick>1294164884</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" MovieMarker="MARK119" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf168.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Unique Model Identifier_41]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test16.xls
Row: 8
Expected value: 
150063369
Matched actual value: 
150063369]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:45]]></Time>
<TimeTick>1294164885</TimeTick>
<NodeArgs eType="User" icon="10" nRep="30" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_41]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="18" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf164.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_3")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:45]]></Time>
<TimeTick>1294164885</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:45]]></Time>
<TimeTick>1294164885</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" MovieMarker="MARK120" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf170.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 4").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="33" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf169.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_4")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:46]]></Time>
<TimeTick>1294164886</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:46]]></Time>
<TimeTick>1294164886</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" MovieMarker="MARK121" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf172.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[searchEngineeredTransgene.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:47]]></Time>
<TimeTick>1294164887</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="41" MovieMarker="MARK122" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[searchEngineeredTransgene.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf173.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebCheckBox("searchEngineeredTransgene")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[searchTargetedModification.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:48]]></Time>
<TimeTick>1294164888</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" MovieMarker="MARK123" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[searchTargetedModification.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf174.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebCheckBox("searchTargetedModification")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[geneName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["p27"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:48]]></Time>
<TimeTick>1294164888</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="47" MovieMarker="MARK124" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[geneName.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf175.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebList("geneName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:48]]></Time>
<TimeTick>1294164888</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" MovieMarker="MARK125" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf176.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Unique Model Identifier_42]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test16.xls
Row: 15
Expected value: 
405
Matched actual value: 
405]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:49]]></Time>
<TimeTick>1294164889</TimeTick>
<NodeArgs eType="User" icon="10" nRep="52" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_42]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="37" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf171.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_3")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:49]]></Time>
<TimeTick>1294164889</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:49]]></Time>
<TimeTick>1294164889</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" MovieMarker="MARK126" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf178.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 4").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="55" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf177.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_4")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:49]]></Time>
<TimeTick>1294164889</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:50]]></Time>
<TimeTick>1294164890</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" MovieMarker="MARK127" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf180.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[piName.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Balmain, Allan"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:50]]></Time>
<TimeTick>1294164890</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" MovieMarker="MARK128" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[piName.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf181.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebList("piName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[modelDescriptor.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Pten"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:51]]></Time>
<TimeTick>1294164891</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="66" MovieMarker="MARK129" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[modelDescriptor.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf182.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebEdit("modelDescriptor")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:51]]></Time>
<TimeTick>1294164891</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="69" MovieMarker="MARK130" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf183.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Unique Model Identifier_43]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test16.xls
Row: 21
Expected value: 
463
Matched actual value: 
463]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:52]]></Time>
<TimeTick>1294164892</TimeTick>
<NodeArgs eType="User" icon="10" nRep="71" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_43]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="59" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf179.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_3")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:52]]></Time>
<TimeTick>1294164892</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:52]]></Time>
<TimeTick>1294164892</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" MovieMarker="MARK131" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf185.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 4").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="74" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf184.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_4")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:52]]></Time>
<TimeTick>1294164892</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:52]]></Time>
<TimeTick>1294164892</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" MovieMarker="MARK132" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf187.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[phenotype.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Tumor"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:53]]></Time>
<TimeTick>1294164893</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="82" MovieMarker="MARK133" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[phenotype.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf188.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebEdit("phenotype")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[searchImageData.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:54]]></Time>
<TimeTick>1294164894</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="85" MovieMarker="MARK134" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[searchImageData.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf189.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebCheckBox("searchImageData")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:54]]></Time>
<TimeTick>1294164894</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="88" MovieMarker="MARK135" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf190.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Unique Model Identifier_44]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test16.xls
Row: 27
Expected value: 
26
Matched actual value: 
26]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:55]]></Time>
<TimeTick>1294164895</TimeTick>
<NodeArgs eType="User" icon="10" nRep="90" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_44]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="78" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf186.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_3")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:55]]></Time>
<TimeTick>1294164895</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[ADVANCED SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:55]]></Time>
<TimeTick>1294164895</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="94" MovieMarker="MARK136" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ADVANCED SEARCH.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf192.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 4").Link("ADVANCED SEARCH")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="93" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_4]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf191.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models_4")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[caMOD - Cancer Models_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:55]]></Time>
<TimeTick>1294164895</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:56]]></Time>
<TimeTick>1294164896</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="98" MovieMarker="MARK137" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Clear.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf194.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Clear")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[searchEngineeredTransgene.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:56]]></Time>
<TimeTick>1294164896</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="101" MovieMarker="MARK138" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[searchEngineeredTransgene.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf195.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebCheckBox("searchEngineeredTransgene")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[carcinogenicInterventionAgentType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Chemical / Drug"]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:57]]></Time>
<TimeTick>1294164897</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="104" MovieMarker="MARK139" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[carcinogenicInterventionAgentType.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf196.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebList("carcinogenicInterventionAgentType")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:57]]></Time>
<TimeTick>1294164897</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="107" MovieMarker="MARK140" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf197.xml]]></Path>
<ASHilite><![CDATA[Browser("caMOD - Cancer Models").Page("caMOD - Cancer Models 3").WebButton("Search")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Unique Model Identifier_45]]></Obj>
<Details ><![CDATA[Spreadsheet: AdvancedSearch_Test16.xls
Row: 33
Expected value: 
124
Matched actual value: 
124]]></Details>
<Time><![CDATA[1/4/2011 - 13:14:59]]></Time>
<TimeTick>1294164899</TimeTick>
<NodeArgs eType="User" icon="10" nRep="109" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Unique Model Identifier_45]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="97" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[caMOD - Cancer Models_3]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf193.xml]]></Path>